### ISSUE TITLE
Does cramp support other ORM?

### ISSUE THREAD

**Issue by gzliudan** [lifo/cramp#69]
Does cramp support other ORM and how to integrate, such as sequel ? Because the latest sqlserver driver(https://github.com/rails-sqlserver/activerecord-sqlserver-adapter) in ActiveRecord 4.2 does not support sqlserver 2005-2008R2, but my application server must support.

**Comment by bigtunacan** [comment]
ActiveRecord is just included as a gem if you need it; there is no tight coupling between Cramp and ActiveRecord as far as I understand, so using Sequel instead should not be an issue.  However, if the only reason for not using ActiveRecord is because you need to support sqlserver 2005-2008R2 you could just use the 3.0.9 version of ActiveRecord instead which is what is being done in the chat example https://github.com/akitaonrails/cramp_chat_demo/blob/master/Gemfile.lock
